"stylelint" succeed identified the missing semicolon:
error: Missing semicolon
Line: 390, Col: 15, Rule: CssSyntaxError

But didn't identified the missing curly brace "}"