Site is live now. However I got a CSS error from all the units, similar to the next one.
error:
CSS linting service request failed for hcp_now_approved_728x90/css/style.css.
Failed to lint CSS due to a server-side exception. Details: Cannot find module '../data/patch.json' Require stack: - /opt/build/repo/node_modules/css-tree/lib/data-patch.js

This is happening just on the Netlify live site, here on Firebase preview I don't get this errors, neither on the local testing.