I still getting this error from Netlify, it seems CSS linting is still an issue:
error:
CSS linting service request failed for hcp_now_approved_728x90/css/style.css.
Failed to lint CSS due to a server-side exception. Details: Cannot find module '../data/patch.json' Require stack: - /opt/build/repo/node_modules/css-tree/lib/data-patch.js